
.\Setup /QUIET /ACTION=REBUILDDATABASE /INSTANCENAME=MSSQLSERVER /SQLSYSADMINACCOUNTS="p2puat\domain admins" /SAPWD=PASSWORD /SQLCOLLATION=SQL_Latin1_General_CP1_CS_AS




Push-Location "c:\program files\microsoft sql server\120\Setup Bootstrap\SQLServer2014"
.\Setup /QUIET /ACTION=REBUILDDATABASE /INSTANCENAME=MSSQLSERVER /SQLSYSADMINACCOUNTS="" /SAPWD=<add password> /SQLCOLLATION=SQL_Latin1_General_CP1_CS_AS